version: "3.9"
services:
  chat-backend: 
    build: ./server
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
  chat-frontend: 
    build: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app